--WEATHER OBSERVATION 1

SELECT CITY,STATE FROM STATION

--WEATHER OBSERVATION 2

SELECT DISTINCT CITY FROM STATION
WHERE ID%2=0

--WEATHER OBSERVATION 3

SELECT COUNT(CITY)-COUNT(DISTINCT CITY) FROM STATION

--WEATHER OBSERVATION 4

SELECT CITY,LENGTH(CITY)
FROM STATION
ORDER BY LENGTH(CITY) ASC , CITY ASC
LIMIT 1;
SELECT CITY,LENGTH(CITY)
FROM STATION
ORDER BY LENGTH(CITY) DESC , CITY ASC
LIMIT 1;

--WEATHER OBSERVATION 5

SELECT DISTINCT CITY FROM STATION
WHERE CITY REGEXP '^[aeiou]';

--WEATHER OBSERVATION 6

SELECT DISTINCT CITY FROM STATION
WHERE CITY REGEXP '[aeiou]$';

--WEATHER OBSERVATION 7

SELECT DISTINCT CITY FROM STATION
WHERE CITY REGEXP '^[aeiou]' AND CITY REGEXP '[aeiou]$';

--WEATHER OBSERVATION 8

SELECT DISTINCT CITY FROM STATION
WHERE CITY NOT REGEXP '^[aeiou]';

--WEATHER OBSERVATION 10

SELECT DISTINCT CITY FROM STATION 
WHERE CITY NOT REGEXP '[aeiou]$';

--WEATHER OBSERVATION 11

SELECT DISTINCT CITY 
FROM STATION 
WHERE CITY NOT REGEXP '^[aeiou]' OR CITY NOT REGEXP '[aeiou]$';

--WEATHER OBSERVATION 12

SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT REGEXP '^[aeiou]' AND CITY NOT REGEXP '[aeiou]$'

--WEATHER OBSERVATON 13

SELECT (salary*months) AS Earnings,COUNT(*)
FROM EMPLOYEE
GROUP BY Earnings
ORDER BY Earnings DESC
LIMIT 1;

--WEATHER OBSERVATION 14

SELECT ROUND(MAX(LAT_N),4)
FROM STATION
WHERE LAT_N<137.2345;

--WEATHER OBSERVATION 15

SELECT ROUND((LONG_W),4)
FROM STATION
WHERE (LAT_N)<137.2345
ORDER BY LAT_N DESC
LIMIT 1;

--WEATHER OBSERVATION 16

SELECT ROUND(MIN(LAT_N),4)
FROM STATION
WHERE LAT_N>38.7780

--WEATHER OBSERVATION 17

SELECT ROUND(LONG_W,4)
FROM STATION
WHERE LAT_N>38.7780
ORDER BY LAT_N ASC
LIMIT 1;

--WEATHER OBSERVATION 13

SELECT ROUND(SUM(LAT_N),4)
FROM STATION
WHERE LAT_N>38.7880 AND LAT_N<137.2345;
